FROM ubuntu:18.04

RUN apt-get update && apt-get install -y unzip curl
RUN cd /tmp && \
  curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip && \
  unzip protoc-3.9.1-linux-x86_64.zip && \
  mv bin/protoc /usr/bin/ && \
  rm -rf *.zip bin/ include
