FROM python:3.9.9-alpine3.15 as base

# install gcc and grpc dependencies
FROM base as builder
RUN apk add --update --no-cache \
    gcc \
    linux-headers \
    make \
    musl-dev \
    python3-dev \
    g++
ENV GRPC_PYTHON_VERSION 1.43.0
RUN python -m pip install --upgrade pip
RUN pip install grpcio==${GRPC_PYTHON_VERSION} \
    grpcio-tools==${GRPC_PYTHON_VERSION} \
    grpcio-reflection==${GRPC_PYTHON_VERSION} \
    grpcio-health-checking==${GRPC_PYTHON_VERSION} \
    grpcio-testing==${GRPC_PYTHON_VERSION}
